name: Backup
on:
  schedule:
    - cron: "4 23 * * 0"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            sudo snap install go --classic
            git clone -b master https://github.com/TomWright/dasel  dasel-core> /dev/null
            cd dasel-core/cmd/dasel
            GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -buildid=" -o ../../../dasel-amd64
            GOOS=linux GOARCH=arm64 go build -trimpath -ldflags "-s -w -buildid=" -o ../../../dasel-arm64
            cd ../../../
            upx --best dasel-amd64 dasel-arm64
            rm -rf dasel-core
            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "dasel amd64 & arm64 binary"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
